### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by thiamsantos** [thiamsantos/potamus#4]
* [x] Checkbox
* [x] Radio
* [x] Button
* [x] Text Field
* [x] Table
* [x] Switch
* [ ] Slider
* [ ] Navbar
* [ ] Carousel
* [ ] Accordion
* [ ] Cards
* [ ] Badges
* [ ] Notify
* [ ] Pagination
* [ ] Loader
* [ ] Dropdown
* [ ] Modal
* [ ] Tab
* [ ] List
* [ ] Tooltip

**Comment by thiamsantos** [comment]
Checkbox, Radio and Select under development.

**Comment by Lucasktrindade** [comment]
Carousel, Accordion e Notify
