### ISSUE TITLE
Create gh-page for the project

### ISSUE THREAD

**Issue by thiamsantos** [thiamsantos/potamus#5]

**Comment by cbsorrilha** [comment]
Hey, i want to help <3

**Comment by thiamsantos** [comment]
Awesome @cbsorrilha \o/

The project already has a [simple page](https://thiamsantos.github.io/potamus/), but if you want to improve it some how, feel free to do that. Open a issue with your suggestion.

In the near future I will add more components, so the page will need update and your help will be more than welcome. ;)
